apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcacapitalportfolios-api
  labels:
    app: mcacapitalportfolios-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcacapitalportfolios-api
  template:
    metadata:
      labels:
        app: mcacapitalportfolios-api
    spec:
      containers:
        - name: mcacapitalportfolios-api
          image: rasteiro11/mcacapitalportfolios-api:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production" 
            - name: ASPNETCORE_URLS
              value: "http://+:5003"
---
apiVersion: v1
kind: Service
metadata:
  name: mcacapitalportfolios-service
  labels:
    app: mcacapitalportfolios-api
spec:
  type: NodePort 
  ports:
    - port: 5003
      targetPort: 5003
      nodePort: 30083
  selector:
    app: mcacapitalportfolios-api


