name: CI Pipeline with Argo CD

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=rasteiro11/mcacapitalportfolios-api
          IMAGE_TAG=$(date +'%Y%m%d%H%M%S')
          docker build -f ./Infrastructure/Docker/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update Kubernetes Manifest
        run: |
          sed -i "s|image: rasteiro11/mcacapitalportfolios-api:.*|image: rasteiro11/mcacapitalportfolios-api:${IMAGE_TAG}|" ./Infrastructure/K8s/mcacapitalportfolios-api.yaml
      
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
      
          git add ./Infrastructure/K8s/mcacapitalportfolios-api.yaml
      
          git diff --cached --quiet || git commit -m "Update image tag to ${IMAGE_TAG}"
      
          git pull --rebase
      
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
